FROM mcr.microsoft.com/devcontainers/python:1-3.11-bullseye

RUN git config --global user.name "camlostCZ"
RUN git config --global user.email "jiri.novak+GIT@gmail.com"

WORKDIR /workspaces/OtherWorld

#COPY ./requirements.txt ./requirements.txt
#RUN pip install --user -r requirements.txt
